FROM node:20

WORKDIR /app

ENV NODE_OPTIONS=--openssl-legacy-provider

COPY package.json ./
RUN npm install
RUN npm install webdav @aws-sdk/client-s3 @aws-sdk/lib-storage @azure/storage-blob @marsaud/smb2

COPY . .

CMD ["node", "docker/live-test/run-live.js"]
